development:
  adapter: postgresql
  encoding: unicode
  database: ServidualPage_development
  pool: 5
  username: postgres 
  password: postgres
  host: localhost
  port: 5432



test:
  adapter: postgresql
  encoding: unicode
  database: ServidualPage_test
  pool: 5
  username: postgres 
  password: postgres
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: ServidualPage_production
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432